version: '3'

services:
  php:
    image: php:7.4-fpm
    restart: always
    volumes:
      - ./php:/app

  nginx:
    image: nginx:1.23.2
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./php:/app
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
